- name: users | mog | remove preinstalled clutter from home directory
  file:
    path: /home/mog/{{ item }}
    state: absent
  with_items:
    - examples.desktop
    - Desktop
    - Documents
    - Downloads
    - Music
    - Pictures
    - Public
    - Templates
    - Videos

- name: users | mog | create personal config directories
  tags: dotfiles,dotfiles-mog
  file:
    path: /home/mog/{{ item.dir }}
    state: directory
    owner: mog
    group: mog
    mode: 0700
  with_items:
    - { dir: .config }
    - { dir: .config/autostart }
    - { dir: .config/bpytop }
    - { dir: .config/gtk-3.0 }
    - { dir: .config/terminator }
    - { dir: .local }
    - { dir: .local/share }
    - { dir: .local/share/applications }
    - { dir: bin }
    - { dir: desktop }
    - { dir: documents }
    - { dir: downloads }
    - { dir: music }
    - { dir: pictures }
    - { dir: projects }
    - { dir: templates }
    - { dir: videos }

- name: users | mog | copy user-dirs.dirs
  tags: dotfiles,dotfiles-mog
  copy:
    src: users/mog/user-dirs.dirs
    dest: /home/mog/.config/user-dirs.dirs
    owner: mog
    group: mog
    mode: 0600
  notify: update_xdg

- name: users | mog | copy personal config files
  tags: dotfiles,dotfiles-mog
  copy:
    src: users/mog/{{ item.src }}
    dest: /home/mog/{{ item.dest }}
    owner: mog
    group: mog
    mode: 0600
  with_items:
    - { src: 'directory_bookmarks', dest: '.config/gtk-3.0/bookmarks' }
    - { src: 'mimeapps.list', dest: '.config/mimeapps.list' }
    - { src: 'ssh_client_config', dest: '.ssh/config' }
    - { src: 'terminator_config', dest: '.config/terminator/config' }

- name: users | mog | copy profile image
  tags: dotfiles,dotfiles-mog
  get_url:
    src: "{{ user_mog_profilepic_url }}"
    dest: /var/lib/AccountsService/icons/mog.png
    owner: root
    group: root
    mode: 0644
