# Load distro-specific variables
- include_vars: "{{ ansible_distribution }}.yml"
  tags: always

- block:
  # User configs
  - import_tasks: users/mog.yml

## desktop environments

  - include_tasks: appearance/fonts.yml
    when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]

  # system setup
  - import_tasks: system_setup/autofs.yml
  - import_tasks: system_setup/tweaks.yml

  # install software
 - import_tasks: software/bitwarden.yml
 - import_tasks: software/caffeine.yml
 - import_tasks: software/codecs.yml
 - import_tasks: software/firefox.yml
  - import_tasks: software/foliate.yml
  - import_tasks: software/glimpse.yml
  - import_tasks: software/google_chrome.yml
  - import_tasks: software/libreoffice.yml
  - import_tasks: software/lutris.yml
  - import_tasks: software/mattermost.yml
  - import_tasks: software/minecraft.yml
  - import_tasks: software/misc_games.yml
  - import_tasks: software/misc_packages.yml
  - import_tasks: software/openshot.yml
  - import_tasks: software/packer.yml
  - import_tasks: software/signal.yml
  - import_tasks: software/solaar.yml
  - import_tasks: software/spotify.yml
  - import_tasks: software/steam.yml
  - import_tasks: software/syncthing.yml
  - import_tasks: software/terraform.yml
  - import_tasks: software/thunderbird.yml
  - import_tasks: software/todoist.yml
  - import_tasks: software/ulauncher.yml
  - import_tasks: software/vagrant.yml
  - import_tasks: software/virtualbox.yml
  - import_tasks: software/vivaldi.yml
  - import_tasks: software/vlc.yml
  - import_tasks: software/xonotic.yml

  rescue:
    - set_fact: task_failed=true
