- name: users | mog | create group
  tags: groups,mog,users
  group:
    name: mog
    state: present

- name: users | mog | create user
  tags: mog,sudo,users
  user:
    name: mog
    group: mog
    groups: adm,ansible,{{ sudo_group }}
    state: present
    comment: "{{ user_mog_name }}"
    password: "{{ user_mog_pass }}"
    shell: /bin/zsh

- name: users | mog | mog | add sudoers file
  tags: mog,settings,mog,sudo,system,users
  copy:
    src: users/sudoers/sudoers_mog
    dest: /etc/sudoers.d/mog
    owner: root
    group: root
    mode: 0440

- name: users | mog | create .ssh directory
  tags: dotfiles,mog,ssh,users
  file:
    path: "{{ item.dir }}"
    state: directory
    owner: mog
    group: mog
    mode: 0700
  with_items:
    - { dir: '/home/mog/.ssh' }

- name: users | mog | config dirs
  tags: dotfiles,users,mog,users,config
  file:
    path: "{{ item }}"
    state: directory
    owner: "mog"
    group: "mog"
    mode: '0700'
  with_items:
    - "/home/mog/.config"
    - "/home/mog/.config/git"
    - "/home/mog/.config/zsh"


- name: users | mog | add public key
  tags: dotfiles,mog,ssh,ssh-keys,users
  authorized_key:
    user: mog
    key: "{{ item }}"
  with_file:
    - users/ssh/pubkeys/aura_id_ed25519.pub
    - users/ssh/pubkeys/azula_id_ed25519.pub
    - users/ssh/pubkeys/katara_id_ed25519.pub

- name: users | mog | configure zsh
  include_tasks: users/zsh.yml
  vars:
    - user_name: mog
    - user_group: mog
    - user_home: "/home/mog"

- name: users | mog | git
  tags: dotfiles,mog,git,users
  template:
    src: gitconfig.j2
    dest: /home/mog/.config/git/config
    owner: mog
    group: mog
    mode: 0775
