# - name: software | firefox | install package
#   tags: packages,firefox,flatpak,workstation-packages
#   become_user: mog
#   flatpak:
#     name: org.mozilla.firefox
#     method: user
#     state: present
#   when: firefox is defined and firefox == true

- name: software | firefox | install package
  tags: packages,firefox,flatpak,workstation-packages
  apt:
    name: firefox
    state: present
  when: firefox is defined and firefox == true