- name: docker | gpg apt key | add key
  tags: gpgkey,repository,docker
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: docker | add repository
  tags: repository,docker
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: docker | remove old packages
  tags: packages,docker
  apt:
    state: absent
    name:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc

- name: docker | install packages
  tags: packages,docker
  apt:
    state: latest
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io

- name: docker | install docker-compose
  tags: packages,docker, docker-compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/1.27.4/docker-compose-Linux-x86_64"
    dest: "/usr/local/bin/docker-compose"
    mode: "0755"
