- name: appearance | fonts | Iosevka | create dir
  file:
    path: /usr/share/fonts/truetype/iosevka/
    state: directory
    owner: 'root'
    group: 'root'
    mode: '0755'

- name: appearance | fonts | Iosevka | download font
  unarchive:
    src: https://github.com/be5invis/Iosevka/releases/download/v4.1.1/ttc-iosevka-4.1.1.zip
    dest: /usr/share/fonts/truetype/iosevka/
    mode: '0644'
    owner: 'root'
    group: 'root'
    remote_src: yes

- name: appearance | fonts | update font cache
  shell: /usr/bin/fc-cache -f
